sonar.projectKey=Ekaterina-Chmil_php-project-9
sonar.organization=ekaterina-chmil

# Указываем, что сканировать нужно текущую папку
sonar.sources=.

# Исключаем тесты и шаблоны из проверки покрытия (чтобы не было 0%),
# Сонар перестанет ругаться на отсутствие тестов
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*

# Указываем язык
sonar.language=php
sonar.sourceEncoding=UTF-8
