<h1>Сайты</h1>

<div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="urls">
        <thead>
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($urls as $url): ?>
            <tr>
                <td><?= htmlspecialchars($url['id']) ?></td>
                <td>
                    <!-- Используем роутер для генерации ссылки -->
                    <a href="<?= $router->urlFor('urls.show', ['id' => $url['id']]) ?>">
                        <?= htmlspecialchars($url['name']) ?>
                    </a>
                </td>
                <td>
                    <?= htmlspecialchars($lastCheck[$url['id']]['created_at'] ?? '') ?>
                </td>
                <td>
                    <?= htmlspecialchars($lastChecks[$url['id']]['status_code'] ?? '') ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
