<!-- Ошибка валидации формы (НЕ flash, а $error!) -->
<?php if (!empty($error)): ?>
    <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
        <h1 class="display-3">Анализатор страниц</h1>
        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        
        <form action="<?= $router->urlFor('urls.store') ?>" method="post" class="row g-2 align-items-center">
            <div class="col-8">
                <label for="url-name" class="visually-hidden">URL для проверки</label>
                <input
                    id="url-name"
                    type="text"
                    name="url[name]"
                    value="<?= htmlspecialchars($urlValue ?? '') ?>"
                    class="form-control form-control-lg"
                    placeholder="https://www.example.com"
                >
            </div>
            <div class="col-2">
                <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
            </div>
        </form>
    </div>
</div>
