<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $title ?? 'Анализатор страниц' ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="min-vh-100 d-flex flex-column">

    <!-- Header (одинаковый для всех) -->
    <header class="flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="<?= $router->urlFor('home') ?>">Анализатор страниц</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="<?= $router->urlFor('home') ?>">Главная</a></li>
                    <li class="nav-item"><a class="nav-link" href="<?= $router->urlFor('urls.index') ?>">Сайты</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Main: СЮДА ВСТАВИТСЯ УНИКАЛЬНЫЙ КОНТЕНТ СТРАНИЦЫ -->
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <?= $content ?>
        </div>
    </main>

    <!-- Footer (одинаковый для всех) -->
    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank" rel="noreferrer">Hexlet</a>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
